[package]
name = "netproxy"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0"
readme = "README.md"


[dependencies]
clap = { version = "*", features = ["derive"] }
tokio = { version = "*", features = ["full"] }
tokio-native-tls = "*"
log = "*"
env_logger = "*"
